# Generated by Django 4.2.2 on 2023-06-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_recipe_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='difficulty',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='time',
            field=models.IntegerField(default=None),
        ),
    ]
